export const actionTypes = {
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    UPDATE_THEME: 'UPDATE_THEME',
    ADD_NEW_WORK_EXPERIENCE: 'ADD_NEW_WORK_EXPERIENCE',
    UPDATE_WORK_EXPERIENCE: 'UPDATE_WORK_EXPERIENCE',
    UPDATE_WORK_EXPERIENCE_DATA: 'UPDATE_WORK_EXPERIENCE_DATA',
    DELETE_WORK_EXPERIENCE_DATA: 'DELETE_WORK_EXPERIENCE_DATA',
    ADD_DELETED_WORK_EXPERIENCE_ITEM: 'ADD_DELETED_WORK_EXPERIENCE_ITEM',
    ADD_NEW_EDUCATION: 'ADD_NEW_EDUCATION',
    UPDATE_EDUCATION: 'UPDATE_EDUCATION',
    UPDATE_EDUCATION_DATA: 'UPDATE_EDUCATION_DATA',
    DELETE_EDUCATION_DATA: 'DELETE_EDUCATION_DATA',
    ADD_NEW_SKILL: 'ADD_NEW_SKILL',
    UPDATE_SKILL: 'UPDATE_SKILL',
    UPDATE_SKILL_DATA: 'UPDATE_SKILL_DATA',
    DELETE_SKILL_DATA: 'DELETE_SKILL_DATA',

};