export const actionTypes = {
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    UPDATE_THEME: 'UPDATE_THEME',
    ADD_NEW_WORK_EXPERIENCE: 'ADD_NEW_WORK_EXPERIENCE',
    UPDATE_WORK_EXPERIENCE: 'UPDATE_WORK_EXPERIENCE',
    UPDATE_WORK_EXPERIENCE_DATA: 'UPDATE_WORK_EXPERIENCE_DATA',
    DELETE_WORK_EXPERIENCE_DATA: 'DELETE_WORK_EXPERIENCE_DATA',
    ADD_NEW_EDUCATION: 'ADD_NEW_EDUCATION',
    UPDATE_EDUCATION: 'UPDATE_EDUCATION',
    UPDATE_EDUCATION_DATA: 'UPDATE_EDUCATION_DATA',
    DELETE_EDUCATION_DATA: 'DELETE_EDUCATION_DATA',

};